### ISSUE TITLE
1.20.4 Support Please!

### ISSUE THREAD

**Issue by 0zl** [ssquadteam/Geyser-Anvil-Fix#2]
I'm hosting 1.20 (1.20.4) Minecraft Server, tried installing the plugin and it's just vomiting `Could not pass event InventoryOpenEvent`

Is it possible?

Edit: I also got this error when I tried to upgrade from 1.20.4 to 1.20.6:
```
The embedded resource 'geyseranvilfix-Pack.mcpack' cannot be found in plugins/.paper-remapped/Geyser-Anvil-Fix-1.0.0.jar
```

For more context, I'm using Purpur.

**Comment by ssquadteam** [comment]
1.20.4 is not planned. Thought 1.20.6+ works, and the plugin will be updated for future versions as well! And use the [latest download](https://github.com/ssquadteam/Geyser-Anvil-Fix/releases/tag/1.0.1) to fix thee rrors
